### ISSUE TITLE
Bikeshed: come up with a better name for this plugin?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/external-buildkite-buildkite-plugin#4]
I wonder if we can come up with a better name for this plugin?

@staticfloat @maleadt

**Comment by staticfloat** [comment]
How about `external-buildkite-buildkite-plugin`, which will become `JuliaCI/external-buildkite` in the YAML.

Tim, as some background, this package is to support us moving the `.buildkite` directory out of the base Julia repository, since there's too much noise as Dilum and I are experimenting with CI stuff.  It's essentially a git submodule, but with a few fancier features.

**Comment by DilumAluthge** [comment]
> external-buildkite-buildkite-plugin

https://en.wikipedia.org/wiki/Buffalo_buffalo_Buffalo_buffalo_buffalo_buffalo_Buffalo_buffalo
